# Welcome to Jekyll!

# Site settings
title: Digital Fortress
email: leah-nanjala@digitalfortress.com
author: DF

# Copyright setting
copyright: "Unpublished Work (cleft) - {currentYear} {author}"

description: >-
  Welcome to Digital Fortress, where cybersecurity professionals unite to master
  the intricate world of cloud security and drive awareness within the digital
  community. Our mission is to empower individuals with the knowledge, skills,
  and tools necessary to safeguard their digital assets in an ever-evolving cyber
  landscape.

# Base URL settings
baseurl: "/leah-nanjala"
url: "https://leah-nanjala.github.io"

favicon: "/assets/images/favicon.ico"

# Sitemap
sitemap: true

# Theme
theme: jekyll-theme-primer
header:
  overlay_image: /assets/images/banner.jpg
  overlay_filter: 0.3
  actions:
    - label: "View Posts"
      url: "/posts/"

# Encoding and Markdown Processing
encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination setting
paginate: 5
