name: GitHub Pages

on:
  push:
    branches:
      - main  # Updated to use the 'main' branch as the source.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Cache dependencies to speed up builds
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Build and deploy using Jeffrey Tse's Jekyll Deploy Action
      - uses: jeffreytse/jekyll-deploy-action@master
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          repository: ''             # Leave empty to use the current repository
          branch: 'gh-pages'         # Target branch for deployment
          jekyll_src: './'           # Directory containing your Jekyll source
          jekyll_cfg: '_config.yml'  # Path to your _config.yml file
          jekyll_baseurl: ''         # Base URL, leave empty if not using subdirectories
          cname: ''                  # Add your custom domain here if you have one
          actor: ''                  # Defaults to the GITHUB_ACTOR
